export const sampleReport = {
  studentName: "Jordan Rivera",
  intendedMajor: "Computer Science",
  generatedOn: new Date().toISOString(),
  executiveSummary: {
    opportunityRating: "Moderate-High",
    opportunityExplanation:
      "Strong employer demand for software and data roles, multiple career paths available; final outcomes depend heavily on internship conversion and cost management.",
    keyTakeaways: [
      "Prioritize schools with proven internship-to-hire funnels and nearby employer networks.",
      "Compare net price and expected post-grad earnings rather than sticker price alone.",
    ],
    bestFitCareerPaths: ["Software Engineer", "Data Analyst", "Product Manager", "UX Researcher"],
    mainFinancialRisks: ["Overborrowing for unclear ROI", "Ignoring total cost of attendance"],
    recommendedNextSteps: ["Shortlist 6 schools with internship data", "Request net price estimates from each school's financial aid office"],
  },
  majorOverview: {
    whatYouStudy: "Students in Computer Science typically build domain knowledge, problem-solving skills, and practical project experience.",
    commonSkills: ["Critical thinking", "Communication", "Quantitative reasoning", "Project execution"],
    fitProfile: "Students who enjoy structured problem solving, iterative learning, and practical application often fit well.",
  },
  careerPaths: [
    {
      title: "Software Engineer",
      medianSalary: "$95,000",
      projectedGrowth: "Strong",
      requiredEducation: "Bachelor's in CS or related field (internships highly valued)",
      topSkills: ["Algorithmic problem solving", "System design basics", "Code review and testing"],
      whatStudentsUnderestimate:
        "How early internship recruiting cycles start (many open roles for the following summer appear in late summer/fall). Building targeted projects and recruiter-facing resumes in Year 1-2 matters.",
      earlyCareerReality:
        "Expect contract or internship roles first; conversion to full-time depends on internship performance and networking.",
      aiResilienceNote: "Roles that combine systems thinking, cross-team communication, and practical engineering remain resilient; rote implementation tasks are most exposed.",
    },
    {
      title: "Data Analyst",
      medianSalary: "$65,000",
      projectedGrowth: "Steady",
      requiredEducation: "Bachelor's in data, stats, economics, or related field",
      topSkills: ["SQL", "Data cleaning and validation", "Storytelling with data"],
      whatStudentsUnderestimate:
        "The importance of domain knowledge and clear communication—being able to translate analysis to business questions is what advances careers.",
      earlyCareerReality: "Entry roles focus on cleaning pipelines and dashboarding; move to modeling/insights with deliberate project work.",
      aiResilienceNote: "Automation helps with repetitive reporting; analysts who develop domain expertise and communication stand out.",
    },
    {
      title: "Product Manager",
      medianSalary: "$105,000",
      projectedGrowth: "Growing",
      requiredEducation: "Varies—often technical or business undergrad + demonstrated product experience",
      topSkills: ["User research synthesis", "Roadmapping", "Stakeholder communication"],
      whatStudentsUnderestimate:
        "Product roles often require cross-functional experience and the ability to influence without authority; internships that show product sense are rare but valuable.",
      earlyCareerReality: "Often transition from PM internships or from developer roles within a company; expect rotational learning.",
      aiResilienceNote: "Product strategy and stakeholder alignment are human skills less likely to be automated.",
    },
    {
      title: "UX Researcher",
      medianSalary: "$85,000",
      projectedGrowth: "Moderate",
      requiredEducation: "Often a psychology, HCI, or human-centered design background",
      topSkills: ["Interviewing", "Qualitative analysis", "Synthesis and storytelling"],
      whatStudentsUnderestimate: "How project experience and demonstrated reports matter more than grades alone.",
      earlyCareerReality: "Junior roles support larger research agendas and require strong reporting skills.",
      aiResilienceNote: "Empathy and qualitative synthesis are difficult to automate fully.",
    },
  ],
  costAndRoi: {
    inStateVsOutState: "In-state public options often reduce debt pressure and shorten breakeven timelines.",
    publicVsPrivate: "Private institutions can offer value with aid, but net cost must be compared carefully.",
    debtRisk: "Model borrowing conservatively; avoid optimistic salary assumptions.",
    breakevenThinking: "Estimate first-job earnings against total borrowing to understand repayment strain.",
  },
  schoolFit: [
    {
      schoolName: "University of Maryland, College Park",
      estimatedCostCategory: "Moderate (in-state strong value)",
      majorStrength: "Top-ranked regional CS program with broad employer recruitment",
      internshipAccess: "Strong—DC/Baltimore/MD tech employers recruit heavily",
      admissionsRisk: "Moderate—growing applicant pool",
      financialRisk: "Lower for in-state students; out-of-state net price varies",
      notes: "Good balance of research and industry connections; strong internship-to-hire pipelines.",
    },
    {
      schoolName: "Purdue University",
      estimatedCostCategory: "Moderate",
      majorStrength: "Large engineering and CS programs with strong placement",
      internshipAccess: "Strong—Midwest and national recruiters",
      admissionsRisk: "Moderate",
      financialRisk: "Moderate; strong alumni networks and employer pipelines",
      notes: "Particularly strong for systems and engineering tracks; co-op and career fairs are effective.",
    },
    {
      schoolName: "University of Washington",
      estimatedCostCategory: "Moderate-High",
      majorStrength: "Highly ranked CS with deep employer networks (Seattle)",
      internshipAccess: "Very strong—big tech hiring nearby",
      admissionsRisk: "High for OOS applicants",
      financialRisk: "Higher sticker price for out-of-state students",
      notes: "Excellent tech recruiting; consider cost and selectivity trade-offs.",
    },
    {
      schoolName: "UC Irvine",
      estimatedCostCategory: "Moderate",
      majorStrength: "Growing CS program with regional industry ties",
      internshipAccess: "Good—SoCal tech and startups recruit regularly",
      admissionsRisk: "Moderate-High",
      financialRisk: "Depends on aid; in-state residents see better value",
      notes: "Strong for applied AI and data tracks; closer local industry partnerships.",
    },
    {
      schoolName: "UC Davis",
      estimatedCostCategory: "Moderate",
      majorStrength: "Solid CS and engineering offerings; strong STEM advising",
      internshipAccess: "Good—Bay Area and Sacramento connections",
      admissionsRisk: "Moderate",
      financialRisk: "Depends on aid and residency",
      notes: "Good balance of research and practical opportunities.",
    },
    {
      schoolName: "New York University (NYU)",
      estimatedCostCategory: "High",
      majorStrength: "Strong CS and tech programs with high employer access in NYC",
      internshipAccess: "Very strong—finance and tech nearby",
      admissionsRisk: "High",
      financialRisk: "High sticker price; aid varies",
      notes: "Excellent recruiting but higher cost; evaluate net price carefully.",
    },
  ],
  aiRiskAndResilience: {
    aiFieldImpact: "AI automates routine coding and reporting tasks; roles that require synthesis, systems thinking, and cross-team collaboration remain more resilient.",
    resilientSkills: ["Domain depth", "Communication", "Data literacy", "Problem framing"],
    recommendations: ["Add practical project experience", "Build a portfolio with recruiter-facing summaries", "Pursue adaptable tools and collaborative experience"],
  },
  strategyPlan: {
    academicPath: "Choose a core major track and stack practical electives.",
    minorsAndElectives: ["Data analytics", "Communication", "Economics"],
    extracurricularsAndProjects: ["Career-relevant club leadership", "Applied projects", "Community initiatives"],
    internshipTimeline: ["Year 1: Exploration", "Year 2: Skill-building internship", "Year 3: Targeted applications", "Year 4: Conversion"],
    skillsToBuildNow: ["Resume iteration", "Interview readiness", "Networking habits"],
  },
  finalActionPlan: {
    next30Days: ["Shortlist schools", "Gather net cost estimates", "Identify role pathways"],
    next6Months: ["Build two portfolio projects", "Apply for exploratory internships", "Refine academic roadmap"],
  },
  whatStudentsOftenOverlook: [
    "Internship recruiting timeline often starts early—build projects and outreach in Year 1-2.",
    "Major-specific outcomes matter more than overall ranking for specialized careers.",
    "Net price (after aid) can change value propositions dramatically—request net price estimates.",
    "Class size and advising capacity affect how quickly you can switch majors or access research opportunities.",
    "Location matters for internship and entry-level recruiting—proximity to employers increases opportunity.",
    "Portfolio projects and applied experience often beat pedigree alone for practical roles.",
  ],
  sources: [
    { name: "BLS Occupational Outlook Handbook", url: "https://www.bls.gov/ooh/", accessedOn: new Date().toISOString() },
    { name: "College Scorecard", url: "https://collegescorecard.ed.gov/data/", accessedOn: new Date().toISOString() },
    { name: "O*NET Online", url: "https://www.onetonline.org/", accessedOn: new Date().toISOString() },
  ],
  disclaimers: [
    "This report is for educational planning only and does not guarantee admissions or outcomes.",
    "Estimates are ranges informed by public data; verify financial aid and outcomes directly with schools.",
  ],
};

export type SampleReport = typeof sampleReport;
